Features branch
goldfloored/Hello_Microverse2 pull request #1
Opened 2023-06-05 15:58 UTC by goldfloored

Welcome !

This branch includes the webpage ,the stylelint and a README.md file.

2023-06-05 16:05 UTC, Gambit142 reviewed
Hi @goldfloored 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no review done. Kindly use [inline reviews](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) to make comments on your code. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-05 16:53 UTC, Shisui6 requested changes
Hi @goldfloored, 

# Requires Changes 🍀
You have done a great job so far!👏👏
You still need to work on a few issues before moving on to the next project, but you're almost there🪲!

## Highlights🎯
- Descriptive PR title and summary ✅
- Follows Github flow ✅
- Good commit messages ✅

## Required Changes ♻️
- Kindly update your PR title to be a bit more descriptive. Something like Hello Microverse: Setup sounds a lot better don't you think?💭

_Check the comments under the review._

## Optional suggestions 🪶
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-05 16:53 UTC, Shisui6 commented on README.md
> +-->
Please remove all comments that don't describe the code itself. This helps keep your code clean🙏

2023-06-05 16:53 UTC, Shisui6 commented on README.md
> +> My first project in Microverse
Please remove all lines that start with `>`. These lines are not needed as they are simply comments meant to guide you on how to fill out each section of the readme. Removing these lines makes your readme file look much cleaner🧹

2023-06-05 16:53 UTC, Shisui6 commented on README.md
> +
Please add the `Built with` and `Tech stack` headers and include the technologies used for this project. You can add HTML and CSS

2023-06-05 16:53 UTC, Shisui6 commented on README.md
> +This project is [MIT](./LICENSE) licensed.
Your MIT licence currently links to a 404 page. Please update this section to link to a valid licence. You can follow this [lesson](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) as a guide

2023-06-05 16:53 UTC, Shisui6 commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
Please delete this line, as it is simply a note showing you how to fill this section and should not be present in the final readme

2023-06-05 16:53 UTC, Shisui6 commented on README.md
> +
Please add the contributing section header with a message encouraging people to contribute to your project. Please also update the table of contents to include this section

2023-06-06 07:55 UTC, christianbiring1 approved these changes
Hi @goldfloored , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 

## Highlights
- [ ] Great work on implementing all the changes as requested in by the previous reviewer :+1: 
- [ ] All linters checks are passing :heavy_check_mark: 
- [ ] Descriptive PR `title` :+1: 
## Optional suggestions
- [ ] You may consider being more descriptive in your `summary`, by telling what you have done I mean the changes that were introduced in the PR.
- [ ] Also you may consider adding the correct link to the issues page in your README 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 17:24 UTC, goldfloored commented
Greetings @christianbiring1 
Thank you so much for you review and I appreciate it, 
Have a great day!

2023-06-06 17:24 UTC, merged